### PR TITLE
[WIP] Issue#49: Adding plot_diagnostic functionality.

### PR DESCRIPTION
**Pull request by charlesdrotar**
This PR adds the functionality to use plot_diagnostic() as seen in [Issue#49](https://github.com/tgsmith61591/pmdarima/issues/49). 

It might be worth understanding why we are returning 2 copies of the plots unless we suppress one with invoking type(), but either way this works and printing the type is a minor blemish.

### CODE REVIEW

**Comment by charlesdrotar** [comment]
Looked into AppVeyor failure and it seems unrelated to the changes submitted:

screen shot 2018-11-28 at 11 32 20 pm

**Comment by charlesdrotar** [comment]
So looking at your develop it seems like it has the [old ref to pyramid](https://github.com/tgsmith61591/pmdarima/blob/develop/appveyor.yml#L103). I suspect there may have been some hotfixes or patches in master that need to get pulled into develop for this to work.

Thoughts?

**Comment by tgsmith61591** [comment]
😁 You were right in any case. I had changes on remote I hadn't pushed. Stupid, stupid! Should be all up-to-date now.

Unrelated, Circle is failing while building scikit on PyPy now...

**Comment by charlesdrotar** [comment]
Closing this PR and will code directly on feature branch :).

**Comment by tgsmith61591** [comment]
Being handled on #55

**Pull request closed without merging**
