### PR TITLE
[WIP] Allow passing kwargs to Sarimax if used in auto arima. Fix #146

### LINKED ISSUE #146: simple_differencing
Can you expose the simple_differencing option or allow us to pass kwargs to the ARIMA and SARIMA class instantiation methods into the auto_arima class? This helps in some cases where fitting is prohibitively slow.

### PR DESCRIPTION
**Pull request by dbanda**
Allow passing of kwargs to Sarimax if used. This is useful if you need to use auto arima but would like to pass some arguments to the underlying arima e.g `simple_differencing=True` 

Fixing #146

### CODE REVIEW

**Comment by aaronreidsmith** [comment]
@dbanda We follow the [GitFlow](https://datasift.github.io/gitflow/IntroducingGitFlow.html) model (although we are trying to get off of it with #150...). I changed your target branch to `develop` accordingly. Additionally, until this passes the necessary tests, I am marking it as a work in progress. On that note, however, it looks like some of the tests are failing outside of the scope of your PR. I will look into those to see what the root cause is

**Comment by tgsmith61591** [comment]
RE: the PR itself, it's pretty dangerous to use mutable arguments as defaults for functions or constructors. Since that's a prevalent theme in this PR, I'd suggest considering alternatives...

**Comment by aaronreidsmith** [comment]
@dbanda We fixed the CI/CD issues, so you have a couple things you need to look at with this PR now:

1) You appear to have a few linting errors (see bottom of the output [here](https://circleci.com/gh/tgsmith61591/pmdarima/2444?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link))
2) Address @tgsmith61591's comments about mutable defaults

**Comment by aaronreidsmith** [comment]
I am going to close this due to inactivity.

@dbanda, we'd love to see your work get merged in. We can re-open if you address the issues we've pointed out

**Pull request closed without merging**
